name: Deploiement sur DreamHost
on:
  workflow_dispatch: # Permet le lancement manuel depuis l'onglet Actions
    inputs:
      environment:
        description: 'Environnement cible'
        required: true
        type: choice
        options:
          - manganese-dev
          - manganese-prod
      reason:
        description: 'Raison du déploiement (optionnel)'
        required: false
        default: 'Mise à jour du site'
      dry_run:
        description: 'Simulation seulement (true/false)'
        required: true
        type: boolean # Utilisation du type boolean natif
        default: true

jobs:
  web-deploy:
    name: Déploiement sur ${{ inputs.environment }}
    runs-on: ubuntu-latest
    
    # 🌟 C'est ici que la magie opère : GitHub va charger les variables spécifiques à ce choix
    environment: ${{ inputs.environment }} 

    steps:
    - name: 🚚 Recuperation du code
      uses: actions/checkout@v4
    - name: 📝 Génération du fichier de version
      # Extrait les 7 premiers caractères du hash du commit
      run: echo "<?php define('APP_VERSION', '${GITHUB_SHA::7}');" > core/version.php

    - name: 🚀 Déploiement par rsync (SSH)
      uses: Burnett01/rsync-deployments@7.0.1
      with:
        switches: >-
            -avz --delete
            ${{ inputs.dry_run && '--dry-run' || '' }}
            --exclude='.git/'
            --exclude='.github/'
            --exclude='aurevoir2026/'
            --exclude='http/'
            --exclude='logs/'
            --exclude='storage/'
            --exclude='core/config.php'
        path: ./ # Dossier source (votre dépôt GitHub)
        
        # 🌟 Utilisation de la variable définie dans l'environnement GitHub
        remote_path: ${{ vars.REMOTE_PATH }} # CHEMIN ABSOLU REQUIS
        
        remote_host: ${{ secrets.FTP_SERVER }}
        remote_user: ${{ secrets.FTP_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }} # Utilisation d'une clé SSH (Recommandé)